### ISSUE TITLE
str: std::default::Default` is not satisfied

### ISSUE THREAD

**Issue by mdsohelmia** [huacnlee/gpui-component#103]
error[E0277]: the trait bound `str: std::default::Default` is not satisfied
  --> /Users/sohelmia/.cargo/git/checkouts/zed-23861290b5d2093f/b6a3556/crates/gpui/src/shared_string.rs:14:28
   |
14 |         Self(ArcCow::Owned(Arc::default()))
   |                            ^^^ the trait `std::default::Default` is not implemented for `str`, which is required by `Arc<_, _>: std::default::Default`
   |
   = help: the following other types implement trait `std::default::Default`:
             &mut str
             &str
   = note: required for `Arc<str>` to implement `std::default::Default`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `gpui` (lib) due to 1 previous error

**Comment by huacnlee** [comment]
Use Rust 1.80
