### ISSUE TITLE
Is it possible to implement an animation effect when closing a Modal or Drawer?

### ISSUE THREAD

**Issue by eastack** [huacnlee/gpui-component#148]
I've been reading your code and learning about GPUI and Rust, which has been very helpful to me. I noticed that you recently added functionality for Drawer and Modal, but using them feels a bit off. I finally realized that it's due to the lack of animation when closing them.

I found that the animation for `Modal` is implemented in the `RenderOnce` of `Modal`, and whether the `Modal` is displayed is determined by the `builder` closure stored in the `active_modal` of its parent `StoryWorkspace`. When the `Modal` is created and rendered through this closure, it will have an animation effect. However, when `active_modal` is set to `None`, the `Modal` is no longer rendered directly. I'm not sure if it's possible to implement a closing animation for `Modal` within `GPUI`. Do you have any ideas?

**Comment by huacnlee** [comment]
I will do that, but right now, I have no idea how to do it. 

I need to think about it.

**Comment by huacnlee** [comment]
I have added Notification this day, here is also have same problem.

It only have appear animation but no disappear animation.

https://github.com/huacnlee/gpui-component/pull/149/

**Comment by mikayla-maki** [comment]
I think you could make a fade in / out animation by using a non-repeating `.animation()` and having it adjust the element's opacity. I don't if we've implemented element opacity though :)

**Comment by huacnlee** [comment]
https://github.com/user-attachments/assets/c09adc18-554c-4300-8109-98f3ab183910

https://github.com/huacnlee/gpui-component/pull/191

**Comment by huacnlee** [comment]
I did it to Notification, this component is a `Render` element that can be mutable. 

We Notification is going to close:

1. Modify is `closing` state to `true` and `cx.notify` to render with exit animation. 
2. Start an async delay a time to really close it.
