### ISSUE TITLE
macOS sonoma (14.5) release build failed

### ISSUE THREAD

**Issue by mdsohelmia** [huacnlee/gpui-component#30]
`cargo build --release
warning: profile package spec `cranelift-codegen` in profile `dev` did not match any packages
   Compiling proc-macro2 v1.0.85
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.155
   Compiling autocfg v1.3.0
   Compiling cfg-if v1.0.0
   Compiling serde v1.0.203
   Compiling version_check v0.9.4
   Compiling typeid v1.0.0
   Compiling crossbeam-utils v0.8.20
   Compiling memchr v2.7.2
   Compiling pin-project-lite v0.2.14
   Compiling cc v1.0.99
   Compiling once_cell v1.19.0
error: failed to run custom build command for `crossbeam-utils v0.8.20`

Caused by:
  process didn't exit successfully: `/Users/sohelmia/code/gpui-component/target/release/build/crossbeam-utils-c14bd55cd8f8a0c3/build-script-build` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `proc-macro2 v1.0.85`

Caused by:
  process didn't exit successfully: `/Users/sohelmia/code/gpui-component/target/release/build/proc-macro2-8f930e45149c8974/build-script-build` (signal: 9, SIGKILL: kill)
error: failed to run custom build command for `libc v0.2.155`

Caused by:
  process didn't exit successfully: `/Users/sohelmia/code/gpui-component/target/release/build/libc-69fc1ce02ad5b6cc/build-script-build` (signal: 9, SIGKILL: kill)
error: failed to run custom build command for `serde v1.0.203`

Caused by:
  process didn't exit successfully: `/Users/sohelmia/code/gpui-component/target/release/build/serde-f3318e2d6703a118/build-script-build` (signal: 9, SIGKILL: kill)`

**Comment by huacnlee** [comment]
Check your macOS Development tools install status, you may not installed Xcode and setup the developer tools.

You can read this doc:

https://github.com/zed-industries/zed/blob/main/docs/src/development/macos.md
