### ISSUE TITLE
table: how can I mutate the state in a cell?

### ISSUE THREAD

**Issue by zhaopuming** [huacnlee/gpui-component#319]
For example, I'd like to render a checkbox for a column with boolean value, how can I update the state of table data?

Currently, `render_td` has a immutable reference to `self`, so there's no way to mutate the data related to current td.

```rust
    fn render_td(
        &self,
        row_ix: usize,
        col_ix: usize,
        _cx: &mut ViewContext<Table<Self>>,
    ) 
```

**Comment by huacnlee** [comment]
You must give me more information about what you want to do.

Do you want click checkbox to toggle state? If true, you can checkout something like cx.listener that I was wrote in example.

**Comment by zhaopuming** [comment]
Thanks, I found the cx.listener example and it works :-)
